### ISSUE TITLE
Can't go to a product using website category filters because I get an error 500

### ISSUE THREAD

**Issue by malexgp46** [muralikrishnareddy/web_site_sale_exten#1]
I'm using Odoo 10.0

browse() takes at most 3 arguments (4 given)

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_site_sale_exten/controllers/main.py", line 47, in product
    category = category_obj.with_context(context or {}).browse(cr, uid, int(category))
TypeError: browse() takes at most 3 arguments (4 given)

**Comment by suryotrisongko** [comment]
I think I've solved this issue, by editing the main.py in controllers folder.
pay attention to the @http.route(['/shop/product/………

comment these lines = 

        #if category:
            #category = category_obj.with_context(context or {}).browse(cr, uid, int(category))
            #category = category if category.exists() else False

replace with = 

        if category:
            category = category_obj.browse(int(category)).exists()

cmiiw :)

**Comment by BettoISC** [comment]
I solved this problem by this way as well.

**Comment by BonesCaptain** [comment]
Sorry, **I just needed to restart the odoo service**, but now, there is a new error.

**Error:**
Error to render compiling AST
AttributeError: 'website' object has no attribute 'added_to_cart_product_qty'
Template: 897
Path: /templates/t/t/div/section[1]/div[2]/div[2]/form/div/t[4]/span
Node: <span t-esc="website.added_to_cart_product_qty(product.id)" name="product_added_qty" id="product_added_qty" class="hidden"/>

**Trace:**
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 268, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 775, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 834, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 330, in checked_call
    result.flatten()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1275, in flatten
    self.response.append(self.render())
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1268, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1043, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1063, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: 'website' object has no attribute 'added_to_cart_product_qty'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_897_1165
  File "<template>", line 3, in body_call_content_1164
AttributeError: 'website' object has no attribute 'added_to_cart_product_qty'

Error to render compiling AST
AttributeError: 'website' object has no attribute 'added_to_cart_product_qty'
Template: 897
Path: /templates/t/t/div/section[1]/div[2]/div[2]/form/div/t[4]/span
Node: <span t-esc="website.added_to_cart_product_qty(product.id)" name="product_added_qty" id="product_added_qty" class="hidden"/>

Any solution? Any suggestions? THX.
