### ISSUE TITLE
500 Internal Server Error when I am a visitor of the eshop and not logged in

### ISSUE THREAD

**Issue by tragaz** [muralikrishnareddy/web_site_sale_exten#2]
Hello,

I just installed your module to display stock info on the eshop.
it works well when I am connected to the website.

But if I am a visitor who is not logged in, I cannot see the eshop at all. I get a 500 Internal Server Error message.

I checked the log and I got the following message:
```
Traceback (most recent call last):
  File "/opt/marcopolo/marcopolo-server/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/marcopolo/marcopolo-server/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/marcopolo/marcopolo-server/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/opt/marcopolo/marcopolo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/marcopolo/marcopolo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/marcopolo/marcopolo-server/odoo/http.py", line 329, in checked_call
    result.flatten()
  File "/opt/marcopolo/marcopolo-server/odoo/http.py", line 1259, in flatten
    self.response.append(self.render())
  File "/opt/marcopolo/marcopolo-server/odoo/http.py", line 1252, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_ui_view.py", line 1043, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/marcopolo/marcopolo-server/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/opt/marcopolo/marcopolo-server/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_ui_view.py", line 1063, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: (u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Employees/Employe$
Traceback (most recent call last):
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_website_sale_variants_7764
  File "/opt/marcopolo/custom/addons/web_site_sale_exten/controllers/main.py", line 31, in get_attribute_value_ids_ext
    for p in product.product_variant_ids]
  File "/opt/marcopolo/marcopolo-server/odoo/fields.py", line 913, in __get__
    value = record._cache[self]
  File "/opt/marcopolo/marcopolo-server/odoo/models.py", line 5557, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/marcopolo/marcopolo-server/odoo/fields.py", line 48, in get
    raise self.exception
AccessError: (u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Employees/Employee\$

Error to render compiling AST
AccessError: (u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Employees/Employee\$
Template: website_sale.variants
Path: /templates/t/t
Node: <t t-set="attribute_value_ids" t-value="get_attribute_value_ids(product)"/>
```

Can you check and fixed this problem.
Thank you

**Comment by BettoISC** [comment]
I Solved this issue, just edit the security csv file  ir.model.access.csv, the file contains base.group_user instead of base.group_public, so change it.

`id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_stock_move_base_user,stock_move_base_user,stock.model_stock_move,base.group_public,1,0,0,0
access_stock_warehouse_base_user,stock_warehouse_base_user,stock.model_stock_warehouse,base.group_public,1,0,0,0
access_stock_quant_base_user,stock_quant_base_user,stock.model_stock_quant,base.group_public,1,0,0,0
access_product_uom_base_user,product_uom_base_user,product.model_product_uom,base.group_public,1,0,0,0
access_stock_location_base_user,stock_location_base_user,stock.model_stock_location,base.group_public,1,0,0,0
`

**Comment by tragaz** [comment]
That is great, thanks.
Will update it

**Comment by BonesCaptain** [comment]
I solved this problem.
Thanks.

**Comment by ubuntubots** [comment]
> I Solved this issue, just edit the security csv file ir.model.access.csv, the file contains base.group_user instead of base.group_public, so change it.
> 
> `id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink access_stock_move_base_user,stock_move_base_user,stock.model_stock_move,base.group_public,1,0,0,0 access_stock_warehouse_base_user,stock_warehouse_base_user,stock.model_stock_warehouse,base.group_public,1,0,0,0 access_stock_quant_base_user,stock_quant_base_user,stock.model_stock_quant,base.group_public,1,0,0,0 access_product_uom_base_user,product_uom_base_user,product.model_product_uom,base.group_public,1,0,0,0 access_stock_location_base_user,stock_location_base_user,stock.model_stock_location,base.group_public,1,0,0,0 `

Hello.
I updated from "base.group_user"  to "base.group_public", at /odoo/custom/addons/web_site_sale_exten/security but did not work.

Here is how it looks now:
/odoo/custom/addons/web_site_sale_exten/security$ cat ir.model.access.csv

id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_stock_move_base_user,stock_move_base_user,stock.model_stock_move,base.group_public,1,0,0,0
access_stock_warehouse_base_user,stock_warehouse_base_user,stock.model_stock_warehouse,base.group_public,1,0,0,0
access_stock_quant_base_user,stock_quant_base_user,stock.model_stock_quant,base.group_public,1,0,0,0
access_product_uom_base_user,product_uom_base_user,product.model_product_uom,base.group_public,1,0,0,0
access_stock_location_base_user,stock_location_base_user,stock.model_stock_location,base.group_public,1,0,0,0

What did I do wrong? Please help. Thanks
